#!/usr/bin/env bash
# Shared shell library for the local Intriqo runtime.
# It is sourced by the lifecycle scripts and is also executable for:
#   scripts/intriqo-runtime.sh validate

RUNTIME_SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
INTRIQO_ROOT_DIR=${INTRIQO_ROOT_DIR:-$(cd -- "$RUNTIME_SCRIPT_DIR/.." && pwd)}
INTRIQO_ENV_FILE=${INTRIQO_ENV_FILE:-$INTRIQO_ROOT_DIR/.env}
if [[ "$INTRIQO_ENV_FILE" != /* ]]; then
    INTRIQO_ENV_FILE="$INTRIQO_ROOT_DIR/$INTRIQO_ENV_FILE"
fi

intriqo_refresh_paths() {
    INTRIQO_RUNTIME_ROOT=${INTRIQO_RUNTIME_DIR:-$INTRIQO_ROOT_DIR/.intriqo}
    if [[ "$INTRIQO_RUNTIME_ROOT" != /* ]]; then
        INTRIQO_RUNTIME_ROOT="$INTRIQO_ROOT_DIR/$INTRIQO_RUNTIME_ROOT"
    fi
    INTRIQO_PID_DIR="$INTRIQO_RUNTIME_ROOT/pids"
    INTRIQO_LOG_DIR="$INTRIQO_RUNTIME_ROOT/logs"
    INTRIQO_STATE_DIR="$INTRIQO_RUNTIME_ROOT/state"
}
intriqo_refresh_paths

readonly INTRIQO_LOCKED_MODEL_SHA256=69d7df6a027eebcaa64c227c3ab34d8a9fd44d4a0158264e86c3fb93db960cb5
readonly INTRIQO_LOCKED_THRESHOLD_SHA256=28ebd68f65e255e9c32aa433b609c4dc969402605d936b8d49c357c5979058b2

intriqo_die() {
    echo "intriqo: $*" >&2
    return 1
}

intriqo_warn() {
    echo "intriqo: warning: $*" >&2
}

intriqo_resolve_path() {
    local value=${1:?path is required}
    if [[ "$value" == /* ]]; then
        printf '%s\n' "$value"
    else
        printf '%s/%s\n' "$INTRIQO_ROOT_DIR" "$value"
    fi
}

# Read only KEY=VALUE lines. This intentionally does not source .env, so a
# malformed or untrusted value cannot execute shell code during startup. The
# process environment wins over values from the file.
intriqo_load_env_file() {
    [[ -f "$INTRIQO_ENV_FILE" ]] || return 0
    local line key value line_number=0
    while IFS= read -r line || [[ -n "$line" ]]; do
        line_number=$((line_number + 1))
        line="${line#${line%%[![:space:]]*}}"
        line="${line%${line##*[![:space:]]}}"
        [[ -z "$line" || "$line" == \#* ]] && continue
        if [[ ! "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(.*)$ ]]; then
            intriqo_die "invalid assignment in $INTRIQO_ENV_FILE at line $line_number (expected KEY=VALUE)"
            return 1
        fi
        key=${BASH_REMATCH[1]}
        value=${BASH_REMATCH[2]}
        if [[ -v "$key" && -n "${!key}" ]]; then
            continue
        fi
        if [[ "$value" == \"*\" ]]; then
            [[ "$value" == *\" ]] || { intriqo_die "unterminated quoted value in $INTRIQO_ENV_FILE at line $line_number"; return 1; }
            value=${value:1:${#value}-2}
        elif [[ "$value" == \'*\' ]]; then
            [[ "$value" == *\' ]] || { intriqo_die "unterminated quoted value in $INTRIQO_ENV_FILE at line $line_number"; return 1; }
            value=${value:1:${#value}-2}
        fi
        export "$key=$value"
    done < "$INTRIQO_ENV_FILE"
}

# Load a runtime-owned KEY=VALUE file without executing shell code. This is
# used for development-only service JWTs generated by the launcher. Explicit
# process environment values always win.
intriqo_load_key_value_file() {
    local file=$1 line key value line_number=0
    [[ -f "$file" ]] || return 0
    while IFS= read -r line || [[ -n "$line" ]]; do
        line_number=$((line_number + 1))
        line="${line#${line%%[![:space:]]*}}"
        line="${line%${line##*[![:space:]]}}"
        [[ -z "$line" || "$line" == \#* ]] && continue
        if [[ ! "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(.*)$ ]]; then
            intriqo_die "invalid runtime assignment at line $line_number"
            return 1
        fi
        key=${BASH_REMATCH[1]}
        value=${BASH_REMATCH[2]}
        if [[ -v "$key" && -n "${!key}" ]]; then
            continue
        fi
        if [[ "$value" == \"* ]]; then
            [[ "$value" == *\" ]] || { intriqo_die "unterminated runtime quote at line $line_number"; return 1; }
            value=${value:1:${#value}-2}
        elif [[ "$value" == \'* ]]; then
            [[ "$value" == *\' ]] || { intriqo_die "unterminated runtime quote at line $line_number"; return 1; }
            value=${value:1:${#value}-2}
        fi
        export "$key=$value"
    done < "$file"
}

intriqo_is_bool() {
    case "${1,,}" in
        1|0|true|false|yes|no|on|off) return 0 ;;
        *) return 1 ;;
    esac
}

intriqo_bool() {
    case "${1,,}" in
        1|true|yes|on) return 0 ;;
        *) return 1 ;;
    esac
}

intriqo_is_uint() {
    [[ "$1" =~ ^[0-9]+$ ]]
}

intriqo_require_port() {
    local name=$1 value=$2
    intriqo_is_uint "$value" && (( value >= 1 && value <= 65535 )) || {
        intriqo_die "$name must be an integer from 1 to 65535"
        return 1
    }
}

intriqo_require_file() {
    local name=$1 value=$2
    [[ -n "$value" ]] || { intriqo_die "$name is required"; return 1; }
    [[ ! -L "$value" && -f "$value" ]] || {
        intriqo_die "$name must point to a regular non-symlink file"
        return 1
    }
}

intriqo_require_sha256() {
    local name=$1 value=$2 expected=$3
    [[ -z "$value" || "$value" =~ ^[0-9a-f]{64}$ ]] || {
        intriqo_die "$name must be a lowercase SHA-256 hash"
        return 1
    }
}

intriqo_engine_binary() {
    local candidate prefer_ml=${1:-false}
    if [[ -n "${INTRIQO_ENGINE_BIN:-}" ]]; then
        intriqo_resolve_path "$INTRIQO_ENGINE_BIN"
        return 0
    fi
    if [[ "$prefer_ml" == true ]]; then
        candidate="$INTRIQO_ROOT_DIR/build/runtime-release-ml-integration/engine/intriqo-engine"
        if [[ -x "$candidate" ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    fi
    for candidate in \
        "$INTRIQO_ROOT_DIR/build/intriqo-runtime-release/engine/intriqo-engine" \
        "$INTRIQO_ROOT_DIR/build/runtime-integration/engine/intriqo-engine" \
        "$INTRIQO_ROOT_DIR/build/runtime-release/engine/intriqo-engine" \
        "$INTRIQO_ROOT_DIR/engine/build/intriqo-engine" \
        "$INTRIQO_ROOT_DIR/build/runtime-release-ml-integration/engine/intriqo-engine"; do
        if [[ -x "$candidate" ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    candidate=$(find "$INTRIQO_ROOT_DIR/build" -type f -path '*/engine/intriqo-engine' -perm -u+x -print 2>/dev/null | sort | head -n 1 || true)
    [[ -n "$candidate" ]] && printf '%s\n' "$candidate"
}

intriqo_validate_config() {
    local app_env=${APP_ENV:-development}
    local jwt_secret=${JWT_SECRET_KEY:-}
    local db_url=${DATABASE_URL:-postgresql+asyncpg://intriqo:intriqo_dev@127.0.0.1:5432/intriqo}
    local pg_host=${INTRIQO_POSTGRES_HOST:-127.0.0.1}
    local pg_port=${INTRIQO_POSTGRES_PORT:-5432}
    local api_port=${INTRIQO_API_PORT:-8000}
    local frontend_port=${INTRIQO_FRONTEND_PORT:-5173}
    local startup_timeout=${INTRIQO_STARTUP_TIMEOUT_SECONDS:-60}
    local shutdown_timeout=${INTRIQO_SHUTDOWN_TIMEOUT_SECONDS:-15}
    local engine_enabled=${INTRIQO_ENGINE_ENABLED:-true}
    local engine_mode=${INTRIQO_ENGINE_MODE:-synthetic}
    local engine_sink=${INTRIQO_ENGINE_SINK:-file}
    local ml_enabled=${INTRIQO_ML_ENABLED:-false}
    local value path

    intriqo_is_bool "${DEBUG:-false}" || { intriqo_die "DEBUG must be true/false"; return 1; }
    intriqo_is_bool "$engine_enabled" || { intriqo_die "INTRIQO_ENGINE_ENABLED must be true/false"; return 1; }
    intriqo_is_bool "${INTRIQO_AGENTS_ENABLED:-true}" || { intriqo_die "INTRIQO_AGENTS_ENABLED must be true/false"; return 1; }
    intriqo_is_bool "${INTRIQO_FRONTEND_ENABLED:-true}" || { intriqo_die "INTRIQO_FRONTEND_ENABLED must be true/false"; return 1; }
    intriqo_is_bool "${INTRIQO_ENGINE_NO_PROMISCUOUS:-false}" || { intriqo_die "INTRIQO_ENGINE_NO_PROMISCUOUS must be true/false"; return 1; }
    intriqo_is_bool "$ml_enabled" || { intriqo_die "INTRIQO_ML_ENABLED must be true/false"; return 1; }
    intriqo_is_bool "${INTRIQO_API_RELOAD:-false}" || { intriqo_die "INTRIQO_API_RELOAD must be true/false"; return 1; }
    intriqo_require_port INTRIQO_POSTGRES_PORT "$pg_port"
    intriqo_require_port INTRIQO_API_PORT "$api_port"
    intriqo_require_port INTRIQO_FRONTEND_PORT "$frontend_port"
    intriqo_is_uint "$startup_timeout" && (( startup_timeout > 0 )) || { intriqo_die "INTRIQO_STARTUP_TIMEOUT_SECONDS must be a positive integer"; return 1; }
    intriqo_is_uint "$shutdown_timeout" && (( shutdown_timeout > 0 )) || { intriqo_die "INTRIQO_SHUTDOWN_TIMEOUT_SECONDS must be a positive integer"; return 1; }

    if [[ "$app_env" == production ]]; then
        [[ ${#jwt_secret} -ge 32 && "$jwt_secret" != *CHANGE_ME* && "$jwt_secret" != *change-me* && "$jwt_secret" != *development* ]] || {
            intriqo_die "JWT_SECRET_KEY must be a non-placeholder value of at least 32 characters in production"
            return 1
        }
    fi
    [[ "$db_url" == postgresql+asyncpg://* && "$db_url" != *[[:space:]]* && "$db_url" != *\?* && "$db_url" != *\#* ]] || {
        intriqo_die "DATABASE_URL must be a whitespace-free async PostgreSQL URL without query or fragment"
        return 1
    }
    [[ -n "$pg_host" && "$pg_host" != *[[:space:]]* ]] || { intriqo_die "INTRIQO_POSTGRES_HOST is invalid"; return 1; }

    if intriqo_bool "$engine_enabled"; then
        value=${INTRIQO_ENGINE_EVENT_QUEUE_CAPACITY:-0}
        intriqo_is_uint "$value" && (( value <= 1000000 )) || { intriqo_die "INTRIQO_ENGINE_EVENT_QUEUE_CAPACITY must be an integer from 0 to 1000000"; return 1; }
        case "${INTRIQO_ENGINE_LOG_LEVEL:-info}" in error|info|debug) ;; *) intriqo_die "INTRIQO_ENGINE_LOG_LEVEL must be error, info, or debug"; return 1 ;; esac
        case "$engine_mode" in
            synthetic)
                value=${INTRIQO_ENGINE_SYNTHETIC_PACKETS:-10}
                intriqo_is_uint "$value" && (( value > 0 )) || { intriqo_die "INTRIQO_ENGINE_SYNTHETIC_PACKETS must be positive"; return 1; }
                ;;
            pcap)
                path=$(intriqo_resolve_path "${INTRIQO_ENGINE_SOURCE:-}")
                intriqo_require_file INTRIQO_ENGINE_SOURCE "$path" || return 1
                ;;
            interface)
                [[ -n "${INTRIQO_ENGINE_SOURCE:-}" && "$INTRIQO_ENGINE_SOURCE" != *[[:space:]]* ]] || { intriqo_die "INTRIQO_ENGINE_SOURCE must name an interface"; return 1; }
                ;;
            *) intriqo_die "INTRIQO_ENGINE_MODE must be synthetic, pcap, or interface"; return 1 ;;
        esac
        local engine_bin
        engine_bin=$(intriqo_engine_binary "$(intriqo_bool "$ml_enabled" && echo true || echo false)")
        [[ -n "$engine_bin" && -x "$engine_bin" && ! -L "$engine_bin" ]] || {
            intriqo_die "no executable intriqo-engine build found (set INTRIQO_ENGINE_BIN)"
            return 1
        }
        case "$engine_sink" in
            file) ;;
            http)
                [[ -n "${INTRIQO_CONTROL_PLANE_TOKEN:-}" ]] || { intriqo_die "INTRIQO_CONTROL_PLANE_TOKEN is required for the engine HTTP sink"; return 1; }
                [[ "${INTRIQO_CONTROL_PLANE_URL:-http://127.0.0.1:8000}" == http://* && "${INTRIQO_CONTROL_PLANE_URL:-http://127.0.0.1:8000}" != *[[:space:]]* ]] || { intriqo_die "INTRIQO_CONTROL_PLANE_URL must be a whitespace-free HTTP URL for the engine sink"; return 1; }
                ;;
            *) intriqo_die "INTRIQO_ENGINE_SINK must be file or http"; return 1 ;;
        esac
    fi

    if intriqo_bool "$ml_enabled"; then
        intriqo_bool "$engine_enabled" || { intriqo_die "INTRIQO_ML_ENABLED=true requires INTRIQO_ENGINE_ENABLED=true"; return 1; }
        for value in INTRIQO_ML_MODEL_PATH INTRIQO_ML_THRESHOLD_PATH INTRIQO_ML_FEATURE_SCHEMA_PATH; do
            path=$(intriqo_resolve_path "${!value:-}")
            intriqo_require_file "$value" "$path" || return 1
        done
        path=$(intriqo_resolve_path "${INTRIQO_ML_FEATURE_CONTRACT_PATH:-contracts/features/flow_features_v2.json}")
        intriqo_require_file INTRIQO_ML_FEATURE_CONTRACT_PATH "$path" || return 1
        if [[ -n "${INTRIQO_ML_MODEL_METADATA_PATH:-}" ]]; then
            path=$(intriqo_resolve_path "$INTRIQO_ML_MODEL_METADATA_PATH")
            intriqo_require_file INTRIQO_ML_MODEL_METADATA_PATH "$path" || return 1
        fi
        intriqo_require_sha256 INTRIQO_ML_EXPECTED_MODEL_SHA256 "${INTRIQO_ML_EXPECTED_MODEL_SHA256:-}" "$INTRIQO_LOCKED_MODEL_SHA256"
        intriqo_require_sha256 INTRIQO_ML_EXPECTED_THRESHOLD_SHA256 "${INTRIQO_ML_EXPECTED_THRESHOLD_SHA256:-}" "$INTRIQO_LOCKED_THRESHOLD_SHA256"
        value=${INTRIQO_ML_MAX_DEDUP_ENTRIES:-100000}
        intriqo_is_uint "$value" && (( value > 0 )) || { intriqo_die "INTRIQO_ML_MAX_DEDUP_ENTRIES must be positive"; return 1; }
        value=${INTRIQO_ML_QUEUE_CAPACITY:-256}
        intriqo_is_uint "$value" && (( value > 0 )) || { intriqo_die "INTRIQO_ML_QUEUE_CAPACITY must be positive"; return 1; }
    fi
}

intriqo_prepare_runtime() {
    [[ ! -L "$INTRIQO_RUNTIME_ROOT" ]] || { intriqo_die "INTRIQO_RUNTIME_DIR must not be a symlink"; return 1; }
    mkdir -p "$INTRIQO_PID_DIR" "$INTRIQO_LOG_DIR" "$INTRIQO_STATE_DIR"
}

intriqo_runtime_secrets_file() {
    printf '%s\n' "$INTRIQO_STATE_DIR/service-tokens.env"
}

intriqo_runtime_token_is_fresh() {
    local token=${1:-} refresh_margin=${2:-300}
    INTRIQO_JWT_TOKEN="$token" \
    INTRIQO_JWT_SECRET_KEY="$JWT_SECRET_KEY" \
    INTRIQO_JWT_ALGORITHM="${JWT_ALGORITHM:-HS256}" \
    INTRIQO_JWT_REFRESH_MARGIN_SECONDS="$refresh_margin" \
    "$INTRIQO_PYTHON" - <<'PY'
import os
import time

from jose import jwt

try:
    claims = jwt.decode(
        os.environ.get("INTRIQO_JWT_TOKEN", ""),
        os.environ["INTRIQO_JWT_SECRET_KEY"],
        algorithms=[os.environ["INTRIQO_JWT_ALGORITHM"]],
        options={"require_exp": True},
    )
    expires = claims.get("exp")
    margin = int(os.environ["INTRIQO_JWT_REFRESH_MARGIN_SECONDS"])
    if isinstance(expires, bool) or not isinstance(expires, (int, float)):
        raise ValueError("missing exp")
    if expires <= time.time() + margin:
        raise ValueError("token is near expiry")
except Exception:
    raise SystemExit(1)
PY
}

# Development convenience only: the Control Plane already authenticates JWTs
# using the configured secret and role claims. Generate distinct engine and
# agent identities when the local operator has not supplied tokens. Production
# requires explicit tokens and never writes credentials automatically.
intriqo_bootstrap_service_tokens() {
    local token_file secret_generated=false refresh_margin
    local explicit_control=false explicit_agent=false explicit_operator=false
    local renew_control=false renew_agent=false renew_operator=false

    # Capture ownership before loading the runtime cache. Values from the
    # process environment or .env have already been loaded by the launcher;
    # they are explicit credentials and must never be replaced by this cache.
    [[ -n "${INTRIQO_CONTROL_PLANE_TOKEN:-}" ]] && explicit_control=true
    [[ -n "${INTRIQO_AGENT_TOKEN:-}" ]] && explicit_agent=true
    [[ -n "${INTRIQO_OPERATOR_TOKEN:-}" ]] && explicit_operator=true

    # Production uses only credentials supplied by the deployment. In
    # particular, do not let a development runtime file satisfy this check.
    if [[ "${APP_ENV:-development}" == production ]]; then
        [[ -n "${JWT_SECRET_KEY:-}" && "${JWT_SECRET_KEY}" != *CHANGE_ME* && "${JWT_SECRET_KEY}" != *change-me* && "${JWT_SECRET_KEY}" != *replace-with* ]] || {
            intriqo_die "production requires an explicit JWT_SECRET_KEY"
            return 1
        }
        if [[ -z "${INTRIQO_CONTROL_PLANE_TOKEN:-}" || -z "${INTRIQO_AGENT_TOKEN:-}" ]]; then
            intriqo_die "production requires INTRIQO_CONTROL_PLANE_TOKEN and INTRIQO_AGENT_TOKEN"
            return 1
        fi
        export JWT_SECRET_KEY INTRIQO_CONTROL_PLANE_TOKEN INTRIQO_AGENT_TOKEN
        [[ -z "${INTRIQO_OPERATOR_TOKEN:-}" ]] || export INTRIQO_OPERATOR_TOKEN
        return 0
    fi

    token_file=$(intriqo_runtime_secrets_file)
    intriqo_load_key_value_file "$token_file"
    if [[ -z "${JWT_SECRET_KEY:-}" || "${JWT_SECRET_KEY}" == *CHANGE_ME* || "${JWT_SECRET_KEY}" == *change-me* || "${JWT_SECRET_KEY}" == *replace-with* ]]; then
        JWT_SECRET_KEY=$("$INTRIQO_PYTHON" -c 'import secrets; print(secrets.token_urlsafe(48))')
        export JWT_SECRET_KEY
        secret_generated=true
    fi

    refresh_margin=${INTRIQO_JWT_REFRESH_MARGIN_SECONDS:-300}
    intriqo_is_uint "$refresh_margin" || {
        intriqo_die "INTRIQO_JWT_REFRESH_MARGIN_SECONDS must be a non-negative integer"
        return 1
    }

    # Runtime-owned tokens are checked against the current signing key and
    # refreshed before expiry. Explicit values are deliberately not decoded:
    # their lifecycle belongs to the caller that supplied them.
    if [[ "$explicit_control" == false ]]; then
        if [[ "$secret_generated" == true ]] || ! intriqo_runtime_token_is_fresh "${INTRIQO_CONTROL_PLANE_TOKEN:-}" "$refresh_margin"; then
            renew_control=true
        fi
    fi
    if [[ "$explicit_agent" == false ]]; then
        if [[ "$secret_generated" == true ]] || ! intriqo_runtime_token_is_fresh "${INTRIQO_AGENT_TOKEN:-}" "$refresh_margin"; then
            renew_agent=true
        fi
    fi
    if [[ "$explicit_operator" == false ]]; then
        if [[ "$secret_generated" == true ]] || ! intriqo_runtime_token_is_fresh "${INTRIQO_OPERATOR_TOKEN:-}" "$refresh_margin"; then
            renew_operator=true
        fi
    fi

    if [[ "$secret_generated" == false && "$renew_control" == false && "$renew_agent" == false && "$renew_operator" == false ]]; then
        export JWT_SECRET_KEY
        [[ -z "${INTRIQO_CONTROL_PLANE_TOKEN:-}" ]] || export INTRIQO_CONTROL_PLANE_TOKEN
        [[ -z "${INTRIQO_AGENT_TOKEN:-}" ]] || export INTRIQO_AGENT_TOKEN
        [[ -z "${INTRIQO_OPERATOR_TOKEN:-}" ]] || export INTRIQO_OPERATOR_TOKEN
        return 0
    fi

    mkdir -p "$INTRIQO_STATE_DIR"
    umask 077
    local tmp_file="${token_file}.tmp.$$"
    printf 'JWT_SECRET_KEY=%s\n' "$JWT_SECRET_KEY" > "$tmp_file"
    INTRIQO_JWT_SECRET_KEY="$JWT_SECRET_KEY" \
    INTRIQO_JWT_ALGORITHM="${JWT_ALGORITHM:-HS256}" \
    INTRIQO_JWT_EXPIRE_MINUTES="${JWT_ACCESS_TOKEN_EXPIRE_MINUTES:-30}" \
    INTRIQO_RENEW_CONTROL="$renew_control" \
    INTRIQO_RENEW_AGENT="$renew_agent" \
    INTRIQO_RENEW_OPERATOR="$renew_operator" \
    INTRIQO_EXISTING_CONTROL="${INTRIQO_CONTROL_PLANE_TOKEN:-}" \
    INTRIQO_EXISTING_AGENT="${INTRIQO_AGENT_TOKEN:-}" \
    INTRIQO_EXISTING_OPERATOR="${INTRIQO_OPERATOR_TOKEN:-}" \
    INTRIQO_WRITE_CONTROL="$explicit_control" \
    INTRIQO_WRITE_AGENT="$explicit_agent" \
    INTRIQO_WRITE_OPERATOR="$explicit_operator" \
    "$INTRIQO_PYTHON" - <<'PY' >> "$tmp_file"
import os
from datetime import datetime, timedelta, timezone
from uuid import uuid4

from jose import jwt

now = datetime.now(timezone.utc)
expires = now + timedelta(minutes=int(os.environ["INTRIQO_JWT_EXPIRE_MINUTES"]))
common = {"iat": now, "exp": expires}
for key, subject, role, renew, explicit in (
    ("INTRIQO_CONTROL_PLANE_TOKEN", "ids-engine-local", "AGENT", os.environ["INTRIQO_RENEW_CONTROL"], os.environ["INTRIQO_WRITE_CONTROL"]),
    ("INTRIQO_AGENT_TOKEN", "investigation-agent-local", "AGENT", os.environ["INTRIQO_RENEW_AGENT"], os.environ["INTRIQO_WRITE_AGENT"]),
    ("INTRIQO_OPERATOR_TOKEN", "operator-local", "ANALYST", os.environ["INTRIQO_RENEW_OPERATOR"], os.environ["INTRIQO_WRITE_OPERATOR"]),
):
    if explicit == "true":
        continue
    value = os.environ.get({
        "INTRIQO_CONTROL_PLANE_TOKEN": "INTRIQO_EXISTING_CONTROL",
        "INTRIQO_AGENT_TOKEN": "INTRIQO_EXISTING_AGENT",
        "INTRIQO_OPERATOR_TOKEN": "INTRIQO_EXISTING_OPERATOR",
    }[key], "")
    if renew == "true":
        claims = dict(common, sub=subject, user_id=str(uuid4()), role=role)
        value = jwt.encode(claims, os.environ["INTRIQO_JWT_SECRET_KEY"], algorithm=os.environ["INTRIQO_JWT_ALGORITHM"])
    if value:
        print(f"{key}={value}")
PY
    chmod 600 "$tmp_file"
    mv -f -- "$tmp_file" "$token_file"

    # Replace stale values in the current shell with the values just written.
    # Explicit credentials remain untouched and are intentionally absent from
    # the launcher-owned cache.
    [[ "$explicit_control" == true ]] || unset INTRIQO_CONTROL_PLANE_TOKEN
    [[ "$explicit_agent" == true ]] || unset INTRIQO_AGENT_TOKEN
    [[ "$explicit_operator" == true ]] || unset INTRIQO_OPERATOR_TOKEN
    intriqo_load_key_value_file "$token_file"
    export JWT_SECRET_KEY
    [[ -z "${INTRIQO_CONTROL_PLANE_TOKEN:-}" ]] || export INTRIQO_CONTROL_PLANE_TOKEN
    [[ -z "${INTRIQO_AGENT_TOKEN:-}" ]] || export INTRIQO_AGENT_TOKEN
    [[ -z "${INTRIQO_OPERATOR_TOKEN:-}" ]] || export INTRIQO_OPERATOR_TOKEN
}

intriqo_pid_for() {
    local service=$1 pid_file="$INTRIQO_PID_DIR/$1.pid" pid
    [[ -f "$pid_file" ]] || return 1
    IFS= read -r pid < "$pid_file" || return 1
    intriqo_is_uint "$pid" && (( pid > 0 )) || return 1
    printf '%s\n' "$pid"
}

intriqo_pid_running() {
    kill -0 "$1" 2>/dev/null
}

intriqo_service_running() {
    local service=$1 pid
    pid=$(intriqo_pid_for "$service" 2>/dev/null) || return 1
    intriqo_pid_running "$pid"
}

intriqo_assert_stack_stopped() {
    local service
    for service in control-plane ml-worker agents frontend engine; do
        if intriqo_service_running "$service"; then
            intriqo_die "$service is already running; run scripts/stop-intriqo.sh before starting the stack"
            return 1
        fi
    done
}

intriqo_remove_stale_pid() {
    local service=$1
    if ! intriqo_service_running "$service"; then
        rm -f -- "$INTRIQO_PID_DIR/$service.pid"
    fi
}

intriqo_start_process() {
    local service=$1 log_file=$2
    shift 2
    intriqo_service_running "$service" && { intriqo_die "$service is already running"; return 1; }
    intriqo_remove_stale_pid "$service"
    : > "$log_file"
    setsid --wait -- "$@" >> "$log_file" 2>&1 < /dev/null &
    local pid=$!
    printf '%s\n' "$pid" > "$INTRIQO_PID_DIR/$service.pid"
    printf '%s\n' "$pid"
}

intriqo_wait_pid_exit() {
    local pid=$1 timeout=${2:-15} elapsed=0
    while intriqo_pid_running "$pid"; do
        (( elapsed >= timeout )) && return 1
        sleep 1
        elapsed=$((elapsed + 1))
    done
}

intriqo_stop_process() {
    local service=$1 timeout=${2:-15} pid
    pid=$(intriqo_pid_for "$service" 2>/dev/null) || return 0
    if ! intriqo_pid_running "$pid"; then
        rm -f -- "$INTRIQO_PID_DIR/$service.pid"
        return 0
    fi
    kill -TERM -- "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
    if ! intriqo_wait_pid_exit "$pid" "$timeout"; then
        intriqo_warn "$service did not stop within ${timeout}s; sending SIGKILL"
        kill -KILL -- "-$pid" 2>/dev/null || kill -KILL "$pid" 2>/dev/null || true
        intriqo_wait_pid_exit "$pid" 3 || true
    fi
    rm -f -- "$INTRIQO_PID_DIR/$service.pid"
}

intriqo_compose() {
    docker compose -f "$INTRIQO_ROOT_DIR/docker-compose.yml" "$@"
}

intriqo_wait_for_postgres() {
    local timeout=${1:-60} elapsed=0
    local host=${INTRIQO_POSTGRES_HOST:-127.0.0.1}
    local port=${INTRIQO_POSTGRES_PORT:-5432}
    local user=${POSTGRES_USER:-intriqo}
    local database=${POSTGRES_DB:-intriqo}
    while ! pg_isready -q -h "$host" -p "$port" -U "$user" -d "$database"; do
        (( elapsed >= timeout )) && { intriqo_die "PostgreSQL was not ready within ${timeout}s"; return 1; }
        sleep 1
        elapsed=$((elapsed + 1))
    done
}

intriqo_health_ok() {
    local url=${1:-http://${INTRIQO_API_HOST:-127.0.0.1}:${INTRIQO_API_PORT:-8000}/ready}
    local body
    body=$(curl --fail --silent --show-error --max-time 3 "$url" 2>/dev/null) || return 1
    "$INTRIQO_PYTHON" -c 'import json,sys; value=json.load(sys.stdin); raise SystemExit(0 if value.get("status") in {"ok", "ready"} else 1)' <<< "$body"
}

intriqo_wait_for_health() {
    local timeout=${1:-60} elapsed=0
    local url=${2:-http://${INTRIQO_API_HOST:-127.0.0.1}:${INTRIQO_API_PORT:-8000}/ready}
    while ! intriqo_health_ok "$url"; do
        (( elapsed >= timeout )) && { intriqo_die "Control Plane HTTP readiness failed at $url"; return 1; }
        sleep 1
        elapsed=$((elapsed + 1))
    done
}

intriqo_wait_for_engine_ready() {
    local service_pid=$1 log_file=$2 timeout=${3:-60} elapsed=0
    while :; do
        grep -q 'capture_ready=true' "$log_file" 2>/dev/null && return 0
        # Synthetic and PCAP captures are finite; a complete shutdown is a
        # valid readiness result when it happened after engine startup.
        grep -q 'shutdown status=complete' "$log_file" 2>/dev/null && return 0
        if ! intriqo_pid_running "$service_pid"; then
            intriqo_die "IDS engine exited before becoming ready; see $log_file"
            return 1
        fi
        (( elapsed >= timeout )) && { intriqo_die "IDS engine readiness failed; see $log_file"; return 1; }
        sleep 1
        elapsed=$((elapsed + 1))
    done
}

intriqo_wait_for_ml_ready() {
    local status_file=$1 timeout=${2:-60} elapsed=0 state
    while :; do
        if [[ -f "$status_file" ]]; then
            state=$(
                "$INTRIQO_PYTHON" - "$status_file" <<'PY'
import json
import sys

try:
    with open(sys.argv[1], encoding="utf-8") as stream:
        print(json.load(stream).get("state", ""))
except (OSError, ValueError):
    print("")
PY
            )
            case "$state" in
                READY) return 0 ;;
                FAILED|DEGRADED|DISABLED)
                    intriqo_die "ML worker entered $state; see $INTRIQO_LOG_DIR/ml-worker.log"
                    return 1
                    ;;
            esac
        fi
        if ! intriqo_service_running ml-worker; then
            intriqo_die "ML worker exited before becoming READY; see $INTRIQO_LOG_DIR/ml-worker.log"
            return 1
        fi
        (( elapsed >= timeout )) && { intriqo_die "ML worker readiness failed; see $INTRIQO_LOG_DIR/ml-worker.log"; return 1; }
        sleep 1
        elapsed=$((elapsed + 1))
    done
}

intriqo_choose_python() {
    if [[ -n "${INTRIQO_PYTHON:-}" ]]; then
        printf '%s\n' "$INTRIQO_PYTHON"
    elif [[ -x "$INTRIQO_ROOT_DIR/.venv/bin/python" ]]; then
        printf '%s\n' "$INTRIQO_ROOT_DIR/.venv/bin/python"
    elif [[ -x "$INTRIQO_ROOT_DIR/control-plane/.venv/bin/python" ]]; then
        printf '%s\n' "$INTRIQO_ROOT_DIR/control-plane/.venv/bin/python"
    else
        command -v python3 || command -v python
    fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    set -euo pipefail
    case "${1:-validate}" in
        validate)
            intriqo_load_env_file
            intriqo_refresh_paths
            INTRIQO_PYTHON=$(intriqo_choose_python)
            export INTRIQO_PYTHON
            intriqo_validate_config
            echo "Intriqo configuration is valid."
            ;;
        *)
            echo "Usage: scripts/intriqo-runtime.sh validate" >&2
            exit 2
            ;;
    esac
fi
